### ISSUE TITLE
Retire kubo-as-a-library

### ISSUE THREAD

**Issue by hacdias** [ipfs/kubo#10175]
This is the tracking issue to "get rid" of [`kubo-as-alibrary`](https://github.com/ipfs/kubo/tree/master/docs/examples/kubo-as-a-library). In the long run, we do not want Kubo to be used as a library. Kubo is an IPFS implementation, while the core library parts are living in [Boxo](https://github.com/ipfs/boxo).

```[tasklist]
### Tasks
- [ ] Convert current examples of [`kubo-as-library`](https://github.com/ipfs/kubo/tree/master/docs/examples/kubo-as-a-library) into Boxo examples.
- [ ] If the above is not possible, investigate what needs to be "library-ized" in order to make it possible. It should be possible to combine some pieces together in order to achieve all of the functionality described in the example.
- [ ] Remove `kubo-as-a-library`
```
