### ISSUE TITLE
dag import of CARv2 produces "Error: operation not supported" 

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#10257]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-desktop

### Version

```Text
0.25.0-rc1 but confirmed the same error with  0.18.0  (did not check earlier)
```

### Config

```json
n/a
```

## How to reproduce

Create a CAR with a directory using go-car CLI tool and import it WHILE `ipfs daemon` is running:

```console
$ go install github.com/ipld/go-car/cmd/car@9fae087
$ mkdir test-dir
$ car create --output test.car --version 2 --no-wrap test-dir/
$ ipfs dag import test.car
Error: operation not supported
```

## Analysis 

- This bug occurs when `dag import` RPC is executed over HTTP `/api/v0/dag/import` 
  - There is no error when `ipfs daemon` is off because HTTP is not used in that case and `ipfs` operates on `$IPFS_PATH` repo directly. 
- go-car produces CARv2 by default (`--version 2` is implicit)
  - CARv1 does not cause the problem (`car create --output test.car --version 1 --no-wrap test-dir/` works fine)
- We had no tests for `dag import` of CAR version 2 in online mode

## TODO

- [ ] add test matrix that runs `dag import` in online and offline modes for both CARv1 and CARv2
- [ ] fix CARv2 import

**Comment by hacdias** [comment]
Just notes of where the issue starts:

https://github.com/ipld/go-car/blob/9fae087d01f15270a571570ef86e273978bca0e8/v2/block_reader.go#L82-L84

calls

https://github.com/ipfs/boxo/blob/483bc3957202664227b9f5a48483c78727885078/files/readerfile.go#L78

which fails because the HTTP Request file is not an `io.Seeker`.

**Comment by lidel** [comment]
Thanks! Closing as this is a duplicate of https://github.com/ipfs/kubo/issues/9361 which has ongoing discussion already. Let's continue there.
