### ISSUE TITLE
Enabling AutoTLS feature by default

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#10560]
## Context

In https://github.com/ipfs/kubo/pull/10521 we've introduced opt-in [`AutoTLS` feature](https://github.com/ipfs/kubo/blob/master/docs/config.md#autotls) which uses DNS and [p2p-forge](https://github.com/ipshipyard/p2p-forge) infrastructure run by [Interplanetary Shipyard](https://ipshipyard.com/) to automate TLS setup for [libp2p WebSocket](https://github.com/libp2p/specs/blob/master/websockets/README.md) transport.

This feature will not yield the maximum benefit to the swarm unless it is enabled by default, just like `/webtransport` and `/webrtc-direct` listeners are.

This issue tracks remaining work towards enabling AutoTLS by default.

## TODO

- [x] https://github.com/ipfs/kubo/pull/10521 (landed in kubo 0.32.0-rc1)
- [x] `libp2p.direct` public good infra accepts registrations 
- [x] https://github.com/ipfs/kubo/pull/10566
- [ ] disable `AutoTLS` in `test` profile
- [x] https://github.com/ipfs/kubo/pull/10565 
  - [x] `AutoTLS.AutoWSS` flag that adds catch-all listener `/tcp/400X/tls/sni/*.libp2p.direct/ws` if  `Addresses.*` (swarm, announce, appendAnnounce) have no `/tls/sni` or `/wss` ()
  - [x] `/ws` listener can share the same port as `/tcp` (4001)
    - [ ] https://github.com/libp2p/go-libp2p/pull/2984
- [ ] https://github.com/ipfs/kubo/issues/10570
  - [x] wait for libp2p reachability to be Public: https://github.com/ipshipyard/p2p-forge/pull/4
  - [x] do not attempt getting cert if we depend on `/p2p-circuit` addrs
  - [ ] do not attempt getting cert if the only "public addr" is ipv6 blocked by firewall:  https://github.com/ipshipyard/p2p-forge/issues/7
- [ ] Decide when `AutoTLS.Enabled` is `true` by default
  - [ ] we want to avoid noise due to CI and testing nodes 
    - 💡 idea: if `AutoTLS.Enabled` is not explicitly set in config, delay requesting cert by 1h?
  - [ ] set `AutoTLS.Enabled=false` in `test` profile 
- [ ] Agree if we use `/ipX` or `/dnsX` (https://github.com/ipshipyard/p2p-forge/pull/34#discussion_r1908966798)
- [ ] Kubo itself needs some sort of smoke-test E2E `test/cli` that gets cert from localhost `AutoTLS.CAEndpoint` and confirms it is placed in `IPFS_PATH/p2p-forge-certs/certificates/`
- [ ] `libp2p.direct` [productization by Shipyard](https://www.notion.so/libp2p-direct-2024Q3-infrastructure-revamp-proposal-12f1def342878052890feec3e21b42dc) is finished
- [x] https://github.com/libp2p/specs/pull/639
