### ISSUE TITLE
Enable pubsub by default

### ISSUE THREAD

**Issue by alanshaw** [ipfs/kubo#6621]
In js-ipfs we're integrating gossipsub and moving pubsub out of "experimental" status. There are some changes we want to make to support this:

1. [ ] Enable pubsub by default
    * This will add a small overhead to normal operation of the node but is worth it to allow people to pubsub without having to jump through hoops
2. [x] Add a config option [`Pubsub.Enabled`](https://github.com/ipfs/js-ipfs/blob/master/doc/config.md#pubsub) that will allow power users to **disable** pubsub if necessary (done: https://github.com/ipfs/go-ipfs/pull/8510)
3. [ ] Deprecate `--enable-pubsub-experiment` flag for `ipfs daemon`
    * In js-ipfs we will just remove this, but I understand if you want to continue to support it for a period

**Comment by Stebalien** [comment]
@aschmahmann think you could tackle this?

**Comment by aschmahmann** [comment]
@Stebalien No problem. Any thoughts on deprecating vs removing the experimental flag? Should we deprecate in 0.5.0 and remove and 0.6.0?

**Comment by Stebalien** [comment]
I'd leave it and hide it for now (maybe issue a warning).

**Comment by Stebalien** [comment]
Also:

1. Use pubsub's new built-in discovery system instead of literally putting a block advertising our interest in the topic into the blockstore.
2. Manage pubsub topics. This may involve changing the API. At the moment, calling `pubsub publish` will "join" the topic permanently.
3. Pass `pubsub.WithReadyness(pubsub.MinTopicSize(1))` on publish so we don't publish into the void. We can pass a context with a short (1-10s) timeout to avoid blocking forever.
4. Use the non-deprecated `topic.Publish` function so we can actually pass in a context.

**Comment by Stebalien** [comment]
Other blockers:

* Memory usage: https://github.com/libp2p/go-libp2p-pubsub/issues/350
* Silent when not in use: https://github.com/libp2p/go-libp2p-pubsub/issues/332

**Comment by lidel** [comment]
Note for later:

Many people run `--enable-pubsub-experiment` (or `--enable-namesys-pubsub`) 
and we cannot break their infra when experiment becomes the default.

Right now (go-ipfs 0.8.0), when a flag is removed, go-ipfs returns hard error:

```
$ ipfs daemon --removed-fla
Error: unknown option "removed-flag"
```

**Comment by Stebalien** [comment]
We usually avoid removing flags and just deprecate & ignore them.

**Comment by FledgeXu** [comment]
Any progress about this?

**Comment by lidel** [comment]
Quick update:
- added config flags for enabling pubsub and ipns over pubsub in https://github.com/ipfs/go-ipfs/pull/8510 (ETA: go-ipfs 0.11)
  - the flags are disabled by default
  - CLI ones still work

JS-IPFS will be getting support for Fetch protocol soon (https://github.com/libp2p/js-libp2p/pull/1036), which means we could be leveraging it across the stack. 
This, along with flags in go-ipfs config, enables us to work towards having IPNS over Pubsub active by default (cc https://github.com/ipfs/go-ipfs/issues/7572).

@aschmahmann @Stebalien my understanding is that the main blocker is the lack of "GC for pubsub topics created by IPNS"? I filled [TODO](https://github.com/ipfs/go-ipfs/issues/8586) for that. 

Are there any other blockers?

**Comment by Jorropo** [comment]
This require too much out of goal work so we are gonna kill it in 0.20: https://github.com/ipfs/kubo/issues/9717
