### ISSUE TITLE
Release 0.15

### ISSUE THREAD

**Issue by BigLep** [ipfs/kubo#9152]
# Items to do upon creating the release issue
- [x] Fill in the Meta section
- [x] Assign the issue to the release owner and reviewer.
- [x] Name the issue "Release v0.15.0"
- [x] Set the proper values for X.Y.Z
- [x] Pin the issue

# Meta
* Release owner: @ajnavarro 
* Release reviewer: @Jorropo 
* Expected RC date: 2022-08-18
* Expected final release date:  ~2022-08-25~ 2022-08-29
* Accompanying PR for improving the release process: https://github.com/ipfs/kubo/pull/9213

See the [Kubo release process](https://pl-strflt.notion.site/Kubo-Release-Process-5a5d066264704009a28a79cff93062c4) for more info.

# Initial planning
## Themes
1. Clean up cruft
2. Communicating outwards from IPFS Thing
3. Bitswap
 - Priority: knowledge transfer
 - Finish separation
 - Improve server 
  - Leverage test-plans
  - Final validate by deploying to a Cluster
5. Reframe followup
6. Gateway improvement followups?

## Items we're explicitly not doing
1. Kubo RPC cleanup: https://github.com/ipfs/kubo/issues/9124?
2. Repo consolidation
3. Enabling libp2p resource manager

# Kubo 0.15.0 Release

We're happy to announce Kubo 0.15.0, bla bla...

As usual, this release includes important fixes, some of which may be critical for security. Unless the fix addresses a bug being exploited in the wild, the fix will _not_ be called out in the release notes. Please make sure to update ASAP. See our [release process](https://github.com/ipfs/go-ipfs/tree/master/docs/releases.md#security-fix-policy) for details.

## 🗺 What's left for release

<List of items with PRs and/or Issues to be considered for this release>

## 🔦 Highlights

This is a release mainly with bugfixing and library updates. 
We are improving release speed and cadence trying to have a new release every 5 weeks.

#### #️⃣ Blake support

You can now use `blake3` as a valid hash function: `ipfs block put --mhtype=blake3`.
It uses a 32 bytes default size.
To use other hash length set `mhlen`: `ipfs block put --mhtype=blake3 --mhlen=64`

#### 💉 Fx Options plugin

This adds a plugin interface that lets the plugin modify the fx options that are passed to fx when the app is initialized. 
This means plugins can inject their own implementations of IPFS interfaces.
This enables granular customization of go-ipfs behavior by plugins, such as:

- Bitswap with custom filters (e.g. for CID blocking)
- Custom interface implementations such as Pinner or DAGService
- Dynamic configuration of libp2p ...

Here's an example plugin that overrides the default Pinner with a custom one:

```go
func (p *PinnerPlugin) Options(opts []fx.Option) ([]fx.Option, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	cfg, err := config.LoadDefaultConfig(context.Background())
	if err != nil {
		return nil, fmt.Errorf("loading AWS config: %w", err)
	}
	logger, err := zap.NewProduction()
	if err != nil {
		return nil, fmt.Errorf("constructing logger: %w", err)
	}
	smClient := secretsmanager.NewFromConfig(cfg)
	pinsDB, err := db.NewPinsDB(ctx, logger.Sugar(), smClient)
	if err != nil {
		return nil, fmt.Errorf("constructing PinsDB: %w", err)
	}
	pinner := &pinner.Pinner{PinsDB: pinsDB}
	return append(opts, fx.Replace(fx.Annotate(pinner, fx.As(new(pin.Pinner))))), nil
}
```

Extra plugin info [here](https://github.com/ipfs/kubo/blob/master/docs/plugins.md#fx-experimental).

## ✅ Release Checklist

For each RC published in each stage:

- version string in `version.go` has been updated (in the `release-v0.15.0` branch).
- new commits should be added to the `release-v0.15.0` branch from `master` using `git cherry-pick -x ...`
- tag commit with `v0.15.0-rcN`
- add artifacts to https://dist.ipfs.tech
  1. Make a PR against [ipfs/distributions](https://github.com/ipfs/distributions) with local changes produced by `add-version` (see [usage](https://github.com/ipfs/distributions#usage))
  2. Wait for PR to build artifacts and generate diff
  3. Inspect results, merge if CI is green and the diff looks ok
  4. Wait for `master` branch to build and update DNSLink at https://dist.ipfs.tech
- cut a pre-release on [github](https://github.com/ipfs/kubo/releases) and reuse signed artifacts from https://dist.ipfs.tech/kubo (upload the result of the ipfs/distributions build in the previous step).
- Announce the RC:
  - [x] Create a new post on [Discuss](https://discuss.ipfs.io)
    - This will automatically post to IPFS Discord #ipfs-chatter
    - Examples from the past: [0.14.0](https://discuss.ipfs.io/t/kubo-formerly-go-ipfs-v0-14-0-release-is-out/14794)
  - [x] Pin the topic. You need admin privileges for that.
  - [x] To the _early testers_ listed in [docs/EARLY_TESTERS.md](https://github.com/ipfs/go-ipfs/tree/master/docs/EARLY_TESTERS.md).  Do this by copy/pasting their GitHub usernames and checkboxes as a comment so they get a GitHub notification.  ([example](https://github.com/ipfs/go-ipfs/issues/8176#issuecomment-909356394))

Checklist:

- [x] **Stage 0 - Automated Testing**
  - [x] Upgrade to the latest patch release of Go that CircleCI has published
    - [x] See the list here: https://hub.docker.com/r/cimg/go/tags
    - [x] [ipfs/distributions](https://github.com/ipfs/distributions): bump [this version](https://github.com/ipfs/distributions/blob/master/.tool-versions#L2)
    - [x] [ipfs/kubo](https://github.com/ipfs/kubo): [example PR](https://github.com/ipfs/kubo/pull/8599)
  - [x] Fork a new branch (`release-v0.15.0`) from `master` and make any further release related changes to this branch. If any "non-trivial" changes (see the footnotes of [docs/releases.md](https://github.com/ipfs/go-ipfs/tree/master/docs/releases.md) for a definition) get added to the release, uncheck all the checkboxes and return to this stage.
    - [x] Follow the RC release process to cut the first RC.
    - [x] Bump the version in `version.go` in the `master` branch to `vX.(Y+1).0-dev`.
  - [x] Automated Testing (already tested in CI) - Ensure that all tests are passing, this includes:
    - [x] unit, sharness, cross-build, etc (`make test`)
    - [x] lint (`make test_go_lint`)
    - [x] [interop](https://github.com/ipfs/interop#test-with-a-non-yet-released-version-of-go-ipfs)
    - [x] [go-ipfs-api](https://github.com/ipfs/go-ipfs-api)
    - [x] [go-ipfs-http-client](https://github.com/ipfs/go-ipfs-http-client)
    - [x] [WebUI](https://github.com/ipfs-shipyard/ipfs-webui)
- [x] **Stage 1 - Internal Testing**
  - [x] CHANGELOG.md has been updated (https://github.com/ipfs/kubo/pull/9220)
    - use [`./bin/mkreleaselog`](https://github.com/ipfs/go-ipfs/tree/master/bin/mkreleaselog) to generate a nice starter list
  - [x] Infrastructure Testing:
    - [x] Deploy new version to a subset of Gateways (https://github.com/protocol/bifrost-infra/issues/2046)
    - [x] Deploy new version to a subset of Bootstrappers (https://github.com/protocol/bifrost-infra/issues/2055)
    - [x] Deploy new version to a subset of Cluster nodes (https://github.com/protocol/bifrost-infra/issues/2055)
    - [x] Collect metrics every day. Work with the Infrastructure team to learn of any hiccup
  - [x] IPFS Application Testing -  Run the tests of the following applications:
    - [x] [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop)
      - [x] Ensure the RC is published to [the NPM package](https://www.npmjs.com/package/go-ipfs?activeTab=versions) ([happens automatically, just wait for CI](https://github.com/ipfs/npm-go-ipfs/actions))
      - [x] Upgrade to the RC in [ipfs-desktop](https://github.com/ipfs-shipyard/ipfs-desktop) and push to a branch ([example](https://github.com/ipfs/ipfs-desktop/pull/1826/commits/b0a23db31ce942b46d95965ee6fe770fb24d6bde)), and open a draft PR to track through the final release ([example](https://github.com/ipfs/ipfs-desktop/pull/1826)) https://github.com/ipfs/ipfs-desktop/pull/2240
      - [x] Ensure CI tests pass, repeat for new RCs
    - [x] [IPFS Companion](https://github.com/ipfs-shipyard/ipfs-companion) - @lidel
- [x] **Stage 2 - Community Prod Testing**
  - [x] Documentation
    - [x] Ensure that [CHANGELOG.md](https://github.com/ipfs/go-ipfs/tree/master/CHANGELOG.md) is up to date (https://github.com/ipfs/kubo/pull/9220)
    - [x] Ensure that [README.md](https://github.com/ipfs/go-ipfs/tree/master/README.md)  is up to date
    - [x] Update docs by merging the auto-created PR in https://github.com/ipfs/ipfs-docs/pulls (they are auto-created every 12 hours)
  - [x] Invite the wider community through (link to the release issue):
    - [x] [discuss.ipfs.io](https://discuss.ipfs.io/c/announcements)
    - [x] Matrix
- [x] **Stage 3 - Release**
  - [x] Final preparation
    - [x] Verify that version string in [`version.go`](https://github.com/ipfs/go-ipfs/tree/master/version.go) has been updated.
    - [x] Open a PR merging `release-v0.15.0` into the `release` branch.
      - This should be reviewed by the person who most recently released a version of `go-ipfs`.
	  - Use a merge commit (no rebase, no squash)
    - [x] Prepare the command to use for tagging the merge commit (on the `release` branch) with `v0.15.0`.
      - Use `git tag -s` to ensure the tag is signed
    - [x] Have the tagging command reviewed by the person who most recently released a version of `go-ipfs`
      - This is a dangerous operation, as it is difficult to reverse due to Go modules and automated Docker image publishing
    - [x] Push the tag
      - Use `git push origin <tag>`
      - DO NOT USE `git push --tags`, as it will push ALL of your local tags
      - This should initiate a Docker build in GitHub Actions that publishes a `v0.15.0` tagged Docker image to DockerHub
    - [x] Release published
      - [x] to [dist.ipfs.tech](https://dist.ipfs.tech)
      - [x] to [npm-go-ipfs](https://www.npmjs.com/package/go-ipfs) (done by CI at [ipfs/npm-go-ipfs](https://github.com/ipfs/npm-go-ipfs), but ok to dispatch [this job](https://github.com/ipfs/npm-go-ipfs/actions/workflows/main.yml) manually)
      - [x] to [chocolatey](https://chocolatey.org/packages/go-ipfs) (done by CI at [ipfs/choco-go-ipfs](https://github.com/ipfs/choco-go-ipfs/), but ok to dispatch [this job](https://github.com/ipfs/choco-go-ipfs/actions/workflows/main.yml) manually)
         - [x] Manually run [the release workflow](https://github.com/ipfs/choco-go-ipfs/actions/workflows/main.yml)
         - [x] Wait for Chocolatey to approve the release (usually takes a few hours)
      - [x] to [snap](https://snapcraft.io/ipfs) (done CI at [snap/snapcraft.yaml](https://github.com/ipfs/kubo/blob/master/snap/snapcraft.yaml))
      - [x] to [github](https://github.com/ipfs/go-ipfs/releases)
        - [x] After publishing the GitHub release, run the workflow to attach the release assets: https://github.com/ipfs/go-ipfs/actions/workflows/sync-release-assets.yml
      - [x] to [arch](https://www.archlinux.org/packages/community/x86_64/go-ipfs/) (flag it out of date)
    - [x] Cut a new ipfs-desktop release
  - [x] Get a blog post created 
    - [Submit a request using this form](https://airtable.com/shrNH8YWole1xc70I).
    - Notify marketing in #shared-pl-marketing-requests about the blog entry request (since the form gets spam).
    - Don't mark this as done until the blog entry is live.
  - [x] Broadcasting (link to blog post)
    - [x] Twitter (request in Filecoin Slack channel #shared-pl-marketing-requests)
    - [x] [Reddit](https://reddit.com/r/ipfs)
    - [x] [discuss.ipfs.io](https://discuss.ipfs.io/c/announcements)
      - A bot auto-posts this to Discord and Matrix
- [x] **Post-Release**
  - [x] Merge the `release` branch back into `master`, ignoring the changes to `version.go` (keep the `-dev` version from master).
  - [x] Create an issue using this release issue template for the _next_ release.
  - [x] Make sure any last-minute changelog updates from the blog post make it back into the CHANGELOG.
  - [x] Mark PR draft created for IPFS Desktop as ready for review.
  
## ⁉️ Do you have questions?

The best place to ask your questions about IPFS, how it works and what you can do with it is at [discuss.ipfs.io](http://discuss.ipfs.io). We are also available at the `#ipfs` channel on Freenode, which is also [accessible through our Matrix bridge](https://riot.im/app/#/room/#freenode_#ipfs:matrix.org).

## Release improvements for next time

< Add any release improvements that were observed this cycle here so they can get incorporated into future releases. >

## Items for a separate comment

< Do these as a separate comment to avoid the main issue from getting too large and checkbox updates taking too long. >

### Changelog

https://github.com/ipfs/kubo/blob/master/docs/changelogs/v0.15.md

**Comment by BigLep** [comment]
## 2022-07-26 agenda
1. High level priorities
1. Review on how to add things to board.
1. What are doing with the review items in the "Unknown Priority"?
<img width="985" alt="image" src="https://user-images.githubusercontent.com/85411/181039799-75bd8cfb-1b18-47e5-adb4-78754b40db59.png">
2. Tackle the in-reivew items before new work.  How do we distribute?
3. Review the in-progress items
4. Review the items that are blocked.  Are we doing them now?
5. Review the unprioritized Todo items?  Which can we defer?

**Comment by BigLep** [comment]
2022-08-12 conversation with maintainers: 
1. We need to land the release template issues early week of 2022-08-15.  
2. We'll start the release process on Wednesday, 2022-08-17, during European timezones.  Merges after this will make it into the next release.
3. Items we are attempting to land before...
 - go-libp2p 0.21: https://github.com/ipfs/kubo/pull/9074
 - Blake3
 - Use the Bitswap client/server separation with the unifying polyfill (to test if we broken anything)
 - Ian's Gateway interface shrink
 - FX plugin

**Comment by BigLep** [comment]
Release mechanics/template items that should get finished before the release:
- [ ] https://github.com/ipfs/kubo/issues/8576
- [ ] Close out https://github.com/ipfs/kubo/issues/9032
- [ ] https://github.com/ipfs/kubo/pull/9100
- [ ] https://github.com/ipfs/kubo/pull/9095
- [ ] https://github.com/ipfs/kubo/pull/9153
- [ ] https://github.com/ipfs/kubo/pull/9024

**Comment by BigLep** [comment]
@ajnavarro : I populated the issue description with the latest release template and created https://github.com/ipfs/kubo/pull/9201 for capturing improvements.  Plesee update PR as you notice issues.

**Comment by ajnavarro** [comment]
Early testers ping for RC1 testing

- [ ] pacman.store (@RubenKelevra)
- [ ] Infura (@MichaelMure)
- [ ] Textile (@sanderpick)
- [ ] Pinata (@obo20)
- [ ] RTrade (@postables)
- [ ] QRI (@b5)
- [ ] Siderus (@koalalorenzo)
- [ ] Charity Engine (@rytiss, @tristanolive)
- [ ] Fission (@bmann)
- [ ] OrbitDB (@tabcat)

**Comment by BigLep** [comment]
@ajnavarro : per  2022-08-22 conversation, we need to do the Stage 0 items as well.

Maybe it makes sense to not have the RC items in a separate list but rather have the checklist assume only 1 RC and make a note that certain steps need to be done for each RC.

**Comment by tabcat** [comment]
@ajnavarro I'm no longer maintaining OrbitDB. You can ping @aphelionz from now on unless he says otherwise.

**Comment by aphelionz** [comment]
@ajnavarro Happy to test with OrbitDB. WIll give it a go today

**Comment by BigLep** [comment]
Bifrost deployment issue: https://github.com/protocol/bifrost-infra/issues/2046

**Comment by BigLep** [comment]
2022-08-23 conversation:
1. Open an issue against https://github.com/protocol/bifrost-infra like https://github.com/protocol/bifrost-infra/issues/2046 but spell out all that we want (gateways, bootstrapper, and cluster)
2. Update release template to reference the sample issue
3. Update the release template to have changelog separate comment step as one of the things listed at the top.

**Comment by ajnavarro** [comment]
@BigLep done here: https://github.com/ipfs/kubo/pull/9213/files#diff-583c694f07bb5749a2d4f5c390ac1794b45179dca688a04e12281b8e1a867800

**Comment by BigLep** [comment]
For those following the issue, the 0.15 binaries are out: https://github.com/ipfs/kubo/releases/tag/v0.15.0

We're still closing out the last of the release steps.

**Comment by BigLep** [comment]
Here was the state of https://github.com/orgs/ipfs/projects/16/views/7?filterQuery=iteration%3A%22kubo+0.15%22 before moving things to the next iteration/release.  I attached as XLSX because copy/paste is causing column misalignment that I don't have time to figure out.

[0.15 state.xlsx](https://github.com/ipfs/kubo/files/9453551/0.15.state.xlsx)
