### ISSUE TITLE
Release 0.16

### ISSUE THREAD

**Issue by BigLep** [ipfs/kubo#9237]
# Meta
* Release owner: @galargh  
* Release reviewer: @ajnavarro 
* Expected RC date: ~2022-09-22~ 2022-09-26
* Expected final release date:  ~2022-09-29~ ~2022-10-03~ 2022-10-04
* Accompanying PR for improving the release process: https://github.com/ipfs/kubo/pull/9283

See the [Kubo release process](https://pl-strflt.notion.site/Kubo-Release-Process-5a5d066264704009a28a79cff93062c4) for more info.

# Kubo 0.16.0 Release

We're happy to announce Kubo 0.16.0, bla bla...

As usual, this release includes important fixes, some of which may be critical for security. Unless the fix addresses a bug being exploited in the wild, the fix will _not_ be called out in the release notes. Please make sure to update ASAP. See our [release process](https://github.com/ipfs/go-ipfs/tree/master/docs/releases.md#security-fix-policy) for details.

## 🗺 What's left for release

- [x] https://github.com/ipfs/kubo/pull/9265/
- [x] https://github.com/ipfs/kubo/pull/8927
- [x] https://github.com/ipfs/kubo/pull/9285
- [x] https://github.com/ipfs/kubo/pull/9274 
- [x] https://github.com/ipfs/kubo/pull/8890 
- [x] https://github.com/ipfs/kubo/pull/9293
- [x] https://github.com/ipfs/kubo/pull/9303

Ideal, but not blocking:

- [x] https://github.com/ipfs/kubo/issues/9297
- [ ] https://github.com/ipfs/kubo/pull/9053

## 🔦 Highlights

< top highlights for this release notes. For ANY version (final or RCs) >

## ✅ Release Checklist

- [ ] **Stage 0 - Prerequisites**
  - [x] Ensure that the `What's left for release` section has all the checkboxes checked. If that's not the case, discuss the open items with Kubo maintainers and update the release schedule accordingly.
  - [x] Create `docs-release-vX.Y.Z` branch, open a draft PR and keep updating `docs/RELEASE_ISSUE_TEMPLATE.md` on that branch as you go.
  - [x] Ensure you have [GPG key generated]() and [added to your GitHub account](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account). This will enable you to created signed tags.
  - [ ] Ensure you have [admin access](https://discuss.ipfs.tech/g/admins) to [IPFS Discourse](https://discuss.ipfs.tech/). Admin access is required to globally pin posts and create banners. @2color might be able to assist you.
  - [x] Access to [#bifrost](https://filecoinproject.slack.com/archives/C03MMMF606T) channel in FIL Slack might come in handy. Ask the release reviewer to invite you over.
  - [x] After the release is deployed to our internal infrastructure, you're going to need read access to [IPFS network metrics](https://github.com/protocol/pldw/blob/624f47cf4ec14ad2cec6adf601a9f7b203ef770d/docs/sources/ipfs.md#ipfs-network-metrics) dashboards. Open an access request in https://github.com/protocol/pldw/issues/new/choose if you don't have it yet ([example](https://github.com/protocol/pldw/issues/158)).
  - [x] You're also going to need NPM installed on your system. See [here](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) for instructions.
  - [x] Prepare changelog proposal in [docs/changelogs/vX.Y.md](docs/changelogs).
    - Skip filling out the `### Changelog` section (the one where which lists all the commits and contributors) for now. We will populate it after the release branch is cut.
  - [x] Install ZSH ([instructions](https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH#install-and-set-up-zsh-as-default)). It is needed by the changelog creation script.
  - [x] Ensure you have `kubo` checked out under `$(go env GOPATH)/src/github.com/ipfs/kubo`. This is required by the changelog creation script.
    - If you want your clone to live in a different location, you can symlink it to the expected location by running `mkdir -p $(go env GOPATH)/src/github.com/ipfs && ln -s $(pwd) $(go env GOPATH)/src/github.com/ipfs/kubo`.
  - [x] Ensure that [README.md](https://github.com/ipfs/go-ipfs/tree/master/README.md) is up to date.
- [x] **Stage 1 - Initial Preparations**
  - [x] Upgrade to the latest patch release of Go that CircleCI has published (currently used version: `1.19.1`)
    - [x] See the list here: https://hub.docker.com/r/cimg/go/tags
    - [x] [ipfs/distributions](https://github.com/ipfs/distributions): bump [this version](https://github.com/ipfs/distributions/blob/master/.tool-versions#L2)
    - [x] [ipfs/kubo](https://github.com/ipfs/kubo): [example PR](https://github.com/ipfs/kubo/pull/8599)
  - [x] Fork a new branch (`release-vX.Y.Z`) from `master`.
  - [x] Bump the version in `version.go` in the `master` branch to `vX.(Y+1).0-dev`.
- [x] **Stage 2 - Release Candidate** - _if any [non-trivial](docs/releases.md#footnotes) changes need to be included in the release, return to this stage_
  - [x] Bump the version in `version.go` in the `release-vX.Y.Z` branch to `vX.Y.Z-rcN`.
  - [x] If applicable, add new commits to the `release-vX.Y.Z` branch from `master` using `git cherry-pick -x ...`
      - Note: `release-*` branches are protected. You can do all needed updates on a separated branch (e.g. `wip-release-vX.Y.Z`) and when everything is settled push to `release-vX.Y.Z`
  - [x] Update the [docs/changelogs/vX.Y.md](docs/changelogs) with the new commits and contributors.
    - [x] Run `./bin/mkreleaselog` twice to generate the changelog and copy the output.
      - The first run of the script might be poluted with `git clone` output.
    - [x] Paste the output into the `### Changelog` section of the changelog file inside the `<details><summary></summary></details>` block.
    - [x] Commit the changelog changes.
  - [x] Push the `release-vX.Y.Z` branch to GitHub (`git push origin release-vX.Y.Z`) and create a draft PR targetting `release` branch if it doesn't exist yet ([example](https://github.com/ipfs/kubo/pull/9306)).
  - [x] Wait for CI to run and complete PR checks. All checks should pass.
  - [x] Tag HEAD `release-vX.Y.Z` commit with `vX.Y.Z-rcN` (`git tag -s vX.Y.Z-rcN -m 'Pre-release X.Y.Z-rcn'`)
  - [x] Push the `vX.Y.Z-rcN` tag to GitHub (`git push origin vX.Y.Z-rcN`; DO NOT USE `git push --tags` because it pushes all your local tags).
  - [x] Add artifacts to https://dist.ipfs.tech by making a PR against [ipfs/distributions](https://github.com/ipfs/distributions)
    - [x] Clone the `ipfs/distributions` repo locally.
    - [x] Create a new branch (`kubo-release-vX.Y.Z-rcn`) from `master`.
    - [x] Run `./dist.sh add-version kubo vX.Y.Z-rcN` to add the new version to the `versions` file ([instructions](https://github.com/ipfs/distributions#usage)).
      - If you're adding a new RC, `dist.sh` will print _WARNING: not marking pre-release kubo vX.Y.Z-rc1n as the current version._.
    - [x] Push the `kubo-release-vX.Y.Z-rcn` branch to GitHub and create a PR from that branch ([example](https://github.com/ipfs/distributions/pull/760)).
    - [x] Wait for PR to build artifacts and generate diff (~30min)
    - [x] Inspect results, merge if CI is green and the diff looks ok
    - [x] Wait for `master` branch to build. It will automatically update DNSLink at https://dist.ipfs.tech (~30min)
  - [x] Publish the RC to [the NPM package](https://www.npmjs.com/package/go-ipfs?activeTab=versions) by running https://github.com/ipfs/npm-go-ipfs/actions/workflows/main.yml (it happens automatically but it is safe to speed up the process and kick of a run manually)
  - [x] Cut a pre-release on [GitHub](https://github.com/ipfs/kubo/releases) ([instructions](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release), [example](https://github.com/ipfs/kubo/releases/tag/v0.16.0-rc1))
    - Use `vX.Y.Z-rcN` as the tag.
    - Link to the release issue in the description.
    - Link to the relevant [changelog](https://github.com/ipfs/kubo/blob/master/docs/changelogs/) in the description.
    - Check `This is a pre-release`.
  - [x] Synchronize release artifacts by running [sync-release-assets](https://github.com/ipfs/kubo/actions/workflows/sync-release-assets.yml) workflow.
  - [x] Announce the RC
    - [x] Create a new post on [IPFS Discourse](https://discuss.ipfs.tech). ([example](https://discuss.ipfs.tech/t/kubo-v0-16-0-rc1-release-candidate-is-out/15248))
      - Use `Kubo vX.Y.Z-rcn Release Candidate is out!` as the title.
      - Use `kubo` and `go-ipfs` as topics.
      - Repeat the title as a heading (`##`) in the description.
      - Link to the GitHub Release, binaries on IPNS, docker pull command and release notes in the description.
    - [x] Pin the topic globally so that it stays at the top of the category.
    - [x] If there is no more important banner currently set on Discourse (e.g. IPFS Camp announcement), make the topic into a banner.
    - [x] Check if Discourse post was automatically copied to:
      - [x] IPFS Discord #ipfs-chatter
      - [x] FIL Slack #ipfs-chatter
      - [x] Matrix
    - [x] Mention [early testers](https://github.com/ipfs/go-ipfs/tree/master/docs/EARLY_TESTERS.md) in the comment under the release issue ([example](https://github.com/ipfs/kubo/issues/9237#issuecomment-1258072509)).
- [x] **Stage 3 - Internal Testing**
  - [x] Library Testing.
    - [x] [interop](https://github.com/ipfs/interop)
      - [x] Clone the `ipfs/interop` repo locally.
      - [x] Create a new branch (`kubo-release-vX.Y.Z-rcn`) from `master`.
      - [x] Update `go-ipfs` version to `vX.Y.Z-rcN` in [package.json](https://github.com/ipfs/interop/blob/master/package.json).
      - [x] Run `npm install` locally
      - [x] Push the `kubo-release-vX.Y.Z-rcn` branch to GitHub and create a draft PR from that branch ([example](https://github.com/ipfs/interop/pull/511)).
    - [x] [go-ipfs-api](https://github.com/ipfs/go-ipfs-api)
      - [x] Create a branch with kubo version pinned in the [test setup action](https://github.com/ipfs/go-ipfs-api/blob/master/.github/actions/go-test-setup/action.yml) ([example](https://github.com/ipfs/go-ipfs-api/commit/d156b808cc3aebafba65a38e5dd6993543a50e82)).
      - [x] Ensure that CI is green.
      - [x] Delete the branch.
    - [x] [go-ipfs-http-client](https://github.com/ipfs/go-ipfs-http-client)
      - [x] Create a branch with kubo version pinned in the [test setup action](https://github.com/ipfs/go-ipfs-http-client/blob/master/.github/actions/go-test-setup/action.yml) ([example](https://github.com/ipfs/go-ipfs-http-client/commit/8a057960d26f1c60fffef09be3b05ec3f2e71bba)).
      - [x] Ensure that CI is green.
      - [x] Delete the branch.
    - [x] [WebUI](https://github.com/ipfs-shipyard/ipfs-webui)
      - [x] Run [CI workflow](https://github.com/ipfs/ipfs-webui/actions/workflows/ci.yml) with `vX.Y.Z-rcN` for the `kubo-version` input.
      - [x] Ensure that CI is green.
  - [x] Infrastructure Testing.
    - [x] Open an issue against [bifrost-infra](https://github.com/protocol/bifrost-infra) ([example](https://github.com/protocol/bifrost-infra/issues/2109)).
      - Spell out all that we want updated - gateways, the bootstraper and the cluster/preload nodes
      - Mention @protocol/bifrost-team in the issue if you opened it prior to the release
      - [Optional] Reply under a message about the issue in the #bifrost channel on FIL Slack once the RC is out. Send the message to the channel.
      - [x] Check [metrics](https://protocollabs.grafana.net/d/8zlhkKTZk/gateway-slis-precomputed?orgId=1) every day.
        - Compare the metrics trends week over week.
        - If there is an unexpected variation in the trend, message the #bifrost channel on FIL Slack and ask for help investigation the cause.
  - [x] IPFS Application Testing.
    - [x] [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop)
      - [x] Upgrade to the RC in [ipfs-desktop](https://github.com/ipfs-shipyard/ipfs-desktop)
      - [x] Run `npm install` to update `package-lock.json`.
      - [x] Push to a branch ([example](https://github.com/ipfs/ipfs-desktop/pull/1826/commits/b0a23db31ce942b46d95965ee6fe770fb24d6bde))
      - [x] Open a draft PR to track through the final release ([example](https://github.com/ipfs/ipfs-desktop/pull/1826))
      - [x] Ensure CI tests pass
    - [x] [IPFS Companion](https://github.com/ipfs-shipyard/ipfs-companion)
      - Start kubo daemon of the version to release.
      - Start a fresh chromium or chrome instance using `chromium --user-data-dir=$(mktemp -d)` (macos `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=$(mktemp -d)`)
      - Start a fresh firefox instance using `firefox --profile $(mktemp -d)` (macos `/Applications/Firefox.app/Contents/MacOS/firefox --profile $(mktemp -d)`)
      - Install IPFS Companion from [vendor-specific store](https://github.com/ipfs/ipfs-companion/#readme).
      - Check that the comunication between Kubo daemon and IPFS companion is working properly checking if the number of connected peers changes.
- [x] **Stage 5 - Release** - _ONLY FOR FINAL RELEASE_
  - [x] Prepare the `release` branch.
    - [x] Bump the version in `version.go` in the `release-vX.Y.Z` branch to `vX.Y.Z`.
    - [x] Push the `release-vX.Y.Z` branch to GitHub (`git push origin release-vX.Y.Z`)
    - [x] Mark the PR created from `release-vX.Y.Z` as ready for review.
      - [x] Ensure the PR is targetting `release` branch.
      - [x] Ensure that CI is green.
      - [x] Have release reviewer review the PR.
    - [x] Merge the PR into `release` branch using the `Create a merge commit` (do **NOT** use `Squash and merge` nor `Rebase and merge` because we need to be able to sign the merge commit).
    - [x] Checkout the `release` branch locally.
      - Remember to pull the latest changes.
    - [x] Create a signed tag for the release.
      - [x] Have release reviewer review the subsequent tagging commits you intend to run.
        - This is a dangerous operation, as it is difficult to reverse due to Go modules and automated Docker image publishing
      - [x] Tag HEAD `release` commit with `vX.Y.Z` (`git tag -s vX.Y.Z -m 'Release X.Y.Z'`)
      - [x] Push the `vX.Y.Z` tag to GitHub (`git push origin vX.Y.Z`; DO NOT USE `git push --tags` because it pushes all your local tags).
    - [x] Wait for [Publish docker image](https://github.com/ipfs/kubo/actions/workflows/docker-image.yml) workflow run initiated by the tag push to finish.
  - [x] Add artifacts to https://dist.ipfs.tech by making a PR against [ipfs/distributions](https://github.com/ipfs/distributions)
    - [x] Clone the `ipfs/distributions` repo locally.
    - [x] Create a new branch (`kubo-release-vX.Y.Z`) from `master`.
    - [x] Run `./dist.sh add-version kubo vX.Y.Z` to add the new version to the `versions` file ([instructions](https://github.com/ipfs/distributions#usage)).
    - [x] Push the `kubo-release-vX.Y.Z` branch to GitHub and create a PR from that branch ([example](TODO)).
    - [x] Wait for PR to build artifacts and generate diff (~30min)
    - [x] Inspect results, merge if CI is green and the diff looks ok
    - [x] Wait for `master` branch to build. It will automatically update DNSLink at https://dist.ipfs.tech (~30min)
  - [x] Publish the release to [the NPM package](https://www.npmjs.com/package/go-ipfs?activeTab=versions) by running https://github.com/ipfs/npm-go-ipfs/actions/workflows/main.yml (it happens automatically but it is safe to speed up the process and kick of a run manually)
  - [x] Publish the release to [chocolatey](https://chocolatey.org/packages/go-ipfs) by running https://github.com/ipfs/choco-go-ipfs/actions/workflows/main.yml (it happens automatically but it is safe to speed up the process and kick of a run manually)
      - [ ] ~~Wait for Chocolatey to approve the release (usually takes a few hours)~~
  - [x] Ensure the release is published to [snap](https://snapcraft.io/ipfs)
  - [x] Ensure the release is published to [arch](https://www.archlinux.org/packages/community/x86_64/go-ipfs/) (flag it out of date)
  - [x] Cut the release on [GitHub](https://github.com/ipfs/kubo/releases) ([instructions](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release), [example](TODO))
    - Use `vX.Y.Z` as the tag.
    - Link to the release issue in the description.
    - Copy the relevant [changelog](https://github.com/ipfs/kubo/blob/master/docs/changelogs/) into the release description.
      - Keep the release notes as trim as possible (e.g. remove top headers where possible, [example](https://github.com/ipfs/kubo/releases/tag/v0.15.0))
  - [x] Synchronize release artifacts by running [sync-release-assets](https://github.com/ipfs/kubo/actions/workflows/sync-release-assets.yml) workflow.
  - [x] Announce the RC
    - [x] Create a new post on [IPFS Discourse](https://discuss.ipfs.tech). ([example](TODO))
      - Use `Kubo vX.Y.Z Release is out!` as the title.
      - Use `kubo` and `go-ipfs` as topics.
      - Repeat the title as a heading (`##`) in the description.
      - Link to the GitHub Release, binaries on IPNS, docker pull command and release notes in the description.
    - [x] Pin the topic globally so that it stays at the top of the category.
    - [x] If there is no more important banner currently set on Discourse (e.g. IPFS Camp announcement), make the topic into a banner.
    - [x] Check if Discourse post was automatically copied to:
      - [x] IPFS Discord #ipfs-chatter
      - [x] FIL Slack #ipfs-chatter
      - [x] Matrix
  - [x] Add a link from release notes to Discuss post (like we did here: https://github.com/ipfs/kubo/releases/tag/v0.15.0)
  - [x] Update the draft PR created for [interop](https://github.com/ipfs/interop) to use the new release and mark it as ready for review.
  - [x] Update the draft PR created for [IPFS Desktop](https://github.com/ipfs-shipyard/ipfs-desktop) to use the new release and mark it as ready for review.
  - [x] Update docs by merging the auto-created PR in https://github.com/ipfs/ipfs-docs/pulls ([example](https://github.com/ipfs/ipfs-docs/pull/1263)) (they are created automatically every 12 hours)
  - [x] Get the blog post created and shared
    - [x] Submit a request for blog post creation using [the form](https://airtable.com/shrNH8YWole1xc70I).
      - Notify marketing in #shared-pl-marketing-requests about the blog entry request (since the form tends to go to spam).
      - Don't mark this as done until the blog entry is live.
  - [x] Share link to the release on:
      - [x] Twitter (request in Filecoin Slack channel #shared-pl-marketing-requests)
      - [x] [Reddit](https://reddit.com/r/ipfs)
- [x] **Stage 6 - Post-Release**
  - [x] Merge the `release` branch back into `master`, ignoring the changes to `version.go` (keep the `-dev` version from master).
  - [x] Create an issue using this release issue template for the _next_ release.
  
## ⁉️ Do you have questions?

The best place to ask your questions about IPFS, how it works and what you can do with it is at [discuss.ipfs.io](http://discuss.ipfs.io). We are also available at the `#ipfs` channel on Freenode, which is also [accessible through our Matrix bridge](https://riot.im/app/#/room/#freenode_#ipfs:matrix.org).

## Release improvements for next time

< Add any release improvements that were observed this cycle here so they can get incorporated into future releases. >

## Items for a separate comment

< Do these as a separate comment to avoid the main issue from getting too large and checkbox updates taking too long. >

### Changelog

< changelog generated by bin/mkreleaselog > (add it to a separated comment if it is too big)

### ❤️ Contributors

< list generated by bin/mkreleaselog >

Would you like to contribute to the IPFS project and don't know how? Well, there are a few places you can get started:

- Check the issues with the `help wanted` label in the [ipfs/kubo repo](https://github.com/ipfs/kubo/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
- Join an IPFS All Hands, introduce yourself and let us know where you would like to contribute - https://github.com/ipfs/team-mgmt/#weekly-ipfs-all-hands
- Hack with IPFS and show us what you made! The All Hands call is also the perfect venue for demos, join in and show us what you built
- Join the discussion at [discuss.ipfs.io](https://discuss.ipfs.io/) and help users finding their answers.
- Join the [🚀 IPFS Core Implementations Weekly Sync 🛰](https://github.com/ipfs/team-mgmt/issues/992) and be part of the action!

**Comment by BigLep** [comment]
@ajnavarro @galargh : Slack thread on what's remaining before the release: https://filecoinproject.slack.com/archives/C03L0G3B4RX/p1663819594018819

**Comment by galargh** [comment]
We're moving the RC1 release to Monday (2022-09-26) to give enough headway for merging `What's left for release`. As of now, the rest of the schedule remains unchanged.

**Comment by BigLep** [comment]
Thanks for updating the dates @galargh.  To provide a bit more color, we aren't cutting the RC today because we just wrapped up the must-have work of https://github.com/ipfs/kubo/pull/9274.

We don't do releases on Friday.

Pushing to Monday 2022-09-26 also gives us the ability to get two other items that were almost complete:
- [ ] https://github.com/ipfs/kubo/pull/8890 
- [ ] https://github.com/ipfs/kubo/pull/9293

**Comment by galargh** [comment]
Early testers ping for RC1 testing 😄

- [ ] pacman.store (@RubenKelevra)
- [ ] Infura (@MichaelMure)
- [ ] Textile (@sanderpick)
- [ ] Pinata (@obo20)
- [ ] RTrade (@postables)
- [ ] QRI (@b5)
- [ ] Siderus (@koalalorenzo)
- [ ] Charity Engine (@rytiss, @tristanolive)
- [ ] Fission (@bmann)
- [ ] OrbitDB (@tabcat)

**Comment by BigLep** [comment]
Something that needs to improved for next time in my opinion is working on the changelog before the RC.  Right now someone doesn't see much on what has changes, what they should try, what they should look out for, etc.

**Comment by galargh** [comment]
Agreed, it would be beneficial to have it ready in time for the RC. BTW, here's a draft changelog that @ajnavarro prepared - https://github.com/ipfs/kubo/blob/v0.16.0-rc1/docs/changelogs/v0.16.md. It's also linked from the release. At the very least we should formalise how it gets created.

**Comment by lidel** [comment]
Remaining changelog items added in https://github.com/ipfs/kubo/pull/9315  (ready for review)

**Comment by BigLep** [comment]
Here was the state of https://github.com/orgs/ipfs/projects/16/views/7?filterQuery=iteration%3A%22kubo+0.16%22 efore moving things to the next iteration/release. I attached as XLSX because copy/paste is causing column misalignment that I don't have time to figure out.

[0.16 status on 2022-10-04.xlsx](https://github.com/ipfs/kubo/files/9708055/0.16.status.on.2022-10-04.xlsx)

**Comment by benjistokman** [comment]
The AMD64 version appears to not be an AMD64 binary.

**Comment by Jorropo** [comment]
@benjistokman for which platform ? Macos, Linux, windows, ... ?

**Comment by benjistokman** [comment]
Linux

**Comment by Jorropo** [comment]
@benjistokman it's fine for me, can you show me which one is not amd64 ?
```console
$ curl https://dist.ipfs.tech/kubo/v0.16.0/kubo_v0.16.0_linux-amd64.tar.gz | gzip -d | tar -xf -
$ cd kubo/
$ file ipfs 
ipfs: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=202ba79f9e42d51a7d310edbd97e032d6e955f27, for GNU/Linux 3.2.0, with debug_info, not stripped
```
```console
$ curl https://dist.ipfs.tech/go-ipfs/v0.16.0/go-ipfs_v0.16.0_linux-amd64.tar.gz | gzip -d | tar -xf -
$ cd go-ipfs/
$ file ipfs 
ipfs: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=202ba79f9e42d51a7d310edbd97e032d6e955f27, for GNU/Linux 3.2.0, with debug_info, not stripped
```

**Comment by benjistokman** [comment]
Nevermind I was clicking on the Darwin one. I don't know why but the rest of the binaries didn't load. Sorry.

**Comment by galargh** [comment]
We have successfully release v0.16.0: https://github.com/ipfs/kubo/releases/tag/v0.16.0
