### ISSUE TITLE
Lower default limits in Swarm.ConnMgr

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#9420]
The default limits defined in [Swarm.ConnMgr](https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmconnmgr) are very old, come from the time when network was very small and DHT was not the best (<0.5), and we had no QUIC transports.

We keep hundreds of connections around:

https://github.com/ipfs/kubo/blob/e34c0da2b54238baa5509b1e4e61b43278036d36/config/init.go#L97-L103

Times changed, and these are, arguably, no longer good defaults. Keeping hundreds of connections around introduces various problems such as ambient bandwidth cost due to bitswap gossip. Every peer asking all peers it is connected to if they have every CID it is tryting to fetch

## Proposed change 

Lower the implicit defaults for `Swarm.ConnMgr.LowWater` and `Swarm.ConnMgr.HighWater`.

### What should be the new values?

[Brave](https://github.com/brave/brave-core/blob/f001b2d88f7ec308b49f5bb006045af13a2057cf/components/services/ipfs/ipfs_service_utils.cc#L53-L54) and  [IPFS Desktop](https://github.com/ipfs/ipfs-desktop/blob/f1824160b6468ec2bc45b1585b6165cab3546942/src/daemon/config.js#L99-L100) both run with  lowered limits:

```
Swarm.ConnMgr.LowWater = 20
Swarm.ConnMgr.HighWater = 40
```

Unless there is a good reason to keep these connections around, I would set default to the same values.

## TODO

- [ ] decide on new limits
- [ ] change implicit defaults in [config/init.go](https://github.com/ipfs/kubo/blob/e34c0da2b54238baa5509b1e4e61b43278036d36/config/init.go#L97-L103)
- [ ] create config migration for legacy nodes
  - we've recently removed defaults from user config (https://github.com/brave/brave-browser/issues/13525) but preexisting  nodes have values hardcoded in the config
  - we should run one-time migration that inspects `Swarm.ConnMgr` and removes all fields from the object if they all match legacy defaults:
    ```json
    {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    }
    ```
    This way old nodes will benefit from less chatty bitswap too.
