### ISSUE TITLE
🛣️ Kubo 2023Q2/Q3 Roadmap

### ISSUE THREAD

**Issue by BigLep** [ipfs/kubo#9817]
description:
The goal of this roadmap is to outline the key milestones and deliverables for Kubo over the next two quarters of 2023.

### Tasks
- [x] https://github.com/ipfs/kubo/issues/9818
- [x] https://github.com/ipfs/kubo/issues/9820
- [x] https://github.com/ipfs/kubo/issues/9819
- [x] https://github.com/ipfs/boxo/issues/279

Starmap Link: https://starmap.site/roadmap/github.com/ipfs/kubo/issues/9817#list
